export const data = [
  {
    id: 'ML256',
    name: 'Emily Chen',
    jobTitle: 'Machine Learning Engineer',
    matchScore: '80',
    phone: '+1 (415) 555-0123',
    email: 'emily.chen@techmail.com',
    experience: '6 years',
    previousCompany: 'DeepMind Technologies',
    linkedin: 'https://linkedin.com/in/emilychen',
    github: 'https://github.com/emilychen',
    resume: 'emily_chen_resume.pdf',
    location: 'San Francisco, CA',
    skills: [
      'Machine Learning',
      'Python',
      'TensorFlow',
      'PyTorch',
      'NLP',
      'Deep Learning',
    ],
    education: 'Ph.D. in Computer Science, Stanford University',
    comments: {
      technical:
        'Exceptional expertise in deep learning and NLP. Published researcher.',
      communication:
        'Outstanding presentation skills. Great at explaining complex ML concepts.',
      leadership:
        'Led a team of 4 ML engineers. Mentored junior data scientists.',
    },
    resumeShortlisted: true,
    telephonicScheduled: true,
    telephonicScheduleDateTime: '2025-02-28 11:30 AM',
    telephonicResult: 'Pass',
    shortlistedForTechnical1: true,
  },
  {
    id: 'FSD789',
    name: 'Marcus Rodriguez',
    jobTitle: 'Full Stack Developer',
    matchScore: '75',
    phone: '+1 (628) 555-0456',
    email: 'm.rodriguez@devmail.com',
    experience: '8 years',
    previousCompany: 'Stripe',
    linkedin: 'https://linkedin.com/in/mrodriguez',
    github: 'https://github.com/mrodriguez',
    resume: 'marcus_rodriguez_resume.pdf',
    location: 'Oakland, CA',
    skills: ['React', 'Node.js', 'TypeScript', 'AWS', 'MongoDB', 'GraphQL'],
    education: 'B.S. in Computer Science, UC Berkeley',
    comments: {
      technical:
        'Strong full-stack skills. Expert in React, Node.js, and cloud architecture.',
      communication:
        'Excellent team player. Clear and concise communication style.',
      leadership: 'Successfully led multiple cross-functional teams.',
    },
    resumeShortlisted: true,
    telephonicScheduled: true,
    telephonicScheduleDateTime: '2025-03-01 2:00 PM',
    telephonicResult: 'Pass',
    shortlistedForTechnical1: true,
  },
  {
    id: 'CLD445',
    name: 'Priya Patel',
    jobTitle: 'Cloud Solutions Architect',
    matchScore: '90',
    phone: '+1 (510) 555-0789',
    email: 'priya.p@cloudmail.com',
    experience: '10 years',
    previousCompany: 'Amazon Web Services',
    linkedin: 'https://linkedin.com/in/priyapatel',
    github: 'https://github.com/priyap',
    resume: 'priya_patel_resume.pdf',
    location: 'Seattle, WA',
    skills: ['AWS', 'Azure', 'GCP', 'Kubernetes', 'Terraform', 'Docker'],
    education: 'M.S. in Software Engineering, University of Washington',
    comments: {
      technical:
        'Deep expertise in AWS, Azure, and GCP. Strong system design skills.',
      communication:
        'Excellent client-facing skills. Great at technical documentation.',
      leadership:
        'Led cloud transformation projects for Fortune 500 companies.',
    },
    resumeShortlisted: true,
    telephonicScheduled: true,
    telephonicScheduleDateTime: '2025-03-02 10:00 AM',
    telephonicResult: 'Pass',
    shortlistedForTechnical1: false,
  },
  {
    id: 'SEC334',
    name: 'David Kim',
    jobTitle: 'Security Engineer',
    matchScore: '65',
    phone: '+1 (415) 555-0321',
    email: 'd.kim@securemail.com',
    experience: '7 years',
    previousCompany: 'FireEye',
    linkedin: 'https://linkedin.com/in/davidkim',
    github: 'https://github.com/dkim',
    resume: 'david_kim_resume.pdf',
    location: 'Mountain View, CA',
    skills: [
      'Penetration Testing',
      'CISSP',
      'Security+',
      'Python',
      'Network Security',
    ],
    education: 'B.S. in Information Security, Georgia Tech',
    resumeShortlisted: false,
    telephonicScheduled: false,
    shortlistedForTechnical1: false,
  },
  {
    id: 'UI678',
    name: 'Sofia Martinez',
    jobTitle: 'UI/UX Designer',
    matchScore: '85',
    phone: '+1 (628) 555-0654',
    email: 'sofia.m@designmail.com',
    experience: '5 years',
    previousCompany: 'Figma',
    linkedin: 'https://linkedin.com/in/sofiamartinez',
    resume: 'sofia_martinez_portfolio.pdf',
    location: 'San Jose, CA',
    skills: [
      'Figma',
      'Adobe XD',
      'Sketch',
      'Design Systems',
      'User Research',
      'Prototyping',
    ],
    education: 'BFA in Interaction Design, Rhode Island School of Design',
    comments: {
      technical: 'Expert in Figma, Adobe Suite, and design systems.',
      communication:
        'Strong storytelling abilities. Great at gathering user feedback.',
      leadership: 'Led design sprints and workshops for product teams.',
    },
    resumeShortlisted: true,
    telephonicScheduled: true,
    telephonicScheduleDateTime: '2025-03-04 1:00 PM',
    telephonicResult: 'Fail',
    shortlistedForTechnical1: false,
  },
];
